server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: apiGateway-circuitBreaker1
          uri: https://github.com/DanielaTarifa/Daniela-Tarifa--PatagoniaTest.git
          search-path: config-data

  application:
    name: config-service
